name: fadp_umi

# FADP数据集的配置参数
camera_obs_latency: 0
robot_obs_latency: 0
gripper_obs_latency: 0
dataset_frequeny: 0
obs_down_sample_steps: 1  # FADP使用1（UMI使用3）

low_dim_obs_horizon: 2
img_obs_horizon: 2
action_horizon: 16
ignore_proprioception: False

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    camera0_rgb:
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: rgb
      ignore_by_policy: False
    
    robot0_eef_pos:
      shape: [3]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: ${eval:'(${task.camera_obs_latency} - ${task.robot_obs_latency}) * ${task.dataset_frequeny}'}
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}
    
    robot0_eef_rot_axis_angle:
      raw_shape: [3]
      shape: [6]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: ${eval:'(${task.camera_obs_latency} - ${task.robot_obs_latency}) * ${task.dataset_frequeny}'}
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      rotation_rep: rotation_6d
      ignore_by_policy: ${task.ignore_proprioception}
    
    robot0_gripper_width:
      shape: [1]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: ${eval:'(${task.camera_obs_latency} - ${task.gripper_obs_latency}) * ${task.dataset_frequeny}'}
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

  action: 
    shape: [10]
    horizon: ${task.action_horizon}
    latency_steps: 0
    down_sample_steps: ${task.obs_down_sample_steps}
    rotation_rep: rotation_6d

task_name: &task_name fadp_umi
dataset_path: data/basin_noup/dataset.zarr.zip

pose_repr: &pose_repr
  obs_pose_repr: relative
  action_pose_repr: relative

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.fadp_umi_dataset.FadpUmiDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  cache_dir: null
  pose_repr: *pose_repr
  action_padding: False
  temporally_independent_normalization: False
  repeat_frame_prob: 0.0
  max_duration: null
  seed: 42
  val_ratio: 0.05
